/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DriverLoginRouteImport } from './routes/driver-login'
import { Route as RestaurantLoginRouteImport } from './routes/restaurant-login'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerMenuRouteImport } from './routes/owner.menu'
import { Route as OwnerOrdersRouteImport } from './routes/owner.orders'
import { Route as RestaurantIdRouteImport } from './routes/restaurant.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverLoginRoute = DriverLoginRouteImport.update({
  id: '/driver-login',
  path: '/driver-login',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantLoginRoute = RestaurantLoginRouteImport.update({
  id: '/restaurant-login',
  path: '/restaurant-login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerMenuRoute = OwnerMenuRouteImport.update({
  id: '/owner/menu',
  path: '/owner/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerOrdersRoute = OwnerOrdersRouteImport.update({
  id: '/owner/orders',
  path: '/owner/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantIdRoute = RestaurantIdRouteImport.update({
  id: '/restaurant/$id',
  path: '/restaurant/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/driver-login': typeof DriverLoginRoute
  '/restaurant-login': typeof RestaurantLoginRoute
  '/orders/$id': typeof OrdersIdRoute
  '/owner/menu': typeof OwnerMenuRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/driver-login': typeof DriverLoginRoute
  '/restaurant-login': typeof RestaurantLoginRoute
  '/orders/$id': typeof OrdersIdRoute
  '/owner/menu': typeof OwnerMenuRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/orders': typeof OrdersIndexRoute
  '/owner': typeof OwnerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/driver-login': typeof DriverLoginRoute
  '/restaurant-login': typeof RestaurantLoginRoute
  '/orders/$id': typeof OrdersIdRoute
  '/owner/menu': typeof OwnerMenuRoute
  '/owner/orders': typeof OwnerOrdersRoute
  '/restaurant/$id': typeof RestaurantIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/owner/': typeof OwnerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/driver-login'
    | '/restaurant-login'
    | '/orders/$id'
    | '/owner/menu'
    | '/owner/orders'
    | '/restaurant/$id'
    | '/orders/'
    | '/owner/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/driver-login'
    | '/restaurant-login'
    | '/orders/$id'
    | '/owner/menu'
    | '/owner/orders'
    | '/restaurant/$id'
    | '/orders'
    | '/owner'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/checkout'
    | '/driver-login'
    | '/restaurant-login'
    | '/orders/$id'
    | '/owner/menu'
    | '/owner/orders'
    | '/restaurant/$id'
    | '/orders/'
    | '/owner/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DriverLoginRoute: typeof DriverLoginRoute
  RestaurantLoginRoute: typeof RestaurantLoginRoute
  OrdersIdRoute: typeof OrdersIdRoute
  OwnerMenuRoute: typeof OwnerMenuRoute
  OwnerOrdersRoute: typeof OwnerOrdersRoute
  RestaurantIdRoute: typeof RestaurantIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver-login': {
      id: '/driver-login'
      path: '/driver-login'
      fullPath: '/driver-login'
      preLoaderRoute: typeof DriverLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant-login': {
      id: '/restaurant-login'
      path: '/restaurant-login'
      fullPath: '/restaurant-login'
      preLoaderRoute: typeof RestaurantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/menu': {
      id: '/owner/menu'
      path: '/owner/menu'
      fullPath: '/owner/menu'
      preLoaderRoute: typeof OwnerMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/orders': {
      id: '/owner/orders'
      path: '/owner/orders'
      fullPath: '/owner/orders'
      preLoaderRoute: typeof OwnerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/$id': {
      id: '/restaurant/$id'
      path: '/restaurant/$id'
      fullPath: '/restaurant/$id'
      preLoaderRoute: typeof RestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DriverLoginRoute: DriverLoginRoute,
  RestaurantLoginRoute: RestaurantLoginRoute,
  OrdersIdRoute: OrdersIdRoute,
  OwnerMenuRoute: OwnerMenuRoute,
  OwnerOrdersRoute: OwnerOrdersRoute,
  RestaurantIdRoute: RestaurantIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  OwnerIndexRoute: OwnerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
